### ISSUE TITLE
Install in Laravel < 8.0

### ISSUE THREAD

**Issue by nitogel** [accentinteractive/laravel-logcleaner#1]
Hi. I have an issue with install your package on Laravel 7.30.4
In your composer.json you require "illuminate/collections": "^6.0|^7.0|^8.0", 
but it doesn't exist "illuminate/collections" < 8.0

**Comment by joostvanveen** [comment]
Hi @nitogel,

We removed dependency `illuminate/collections`, so the package should be compatible with Laravel versions from 6 up.
The other depencies are present in both Laravel 6, 7 and 8.

Fixed in bc1888a05c632072f0878ad84a401359397dc6ed

Happy coding!
