### ISSUE TITLE
Does not work on log inside directories

### ISSUE THREAD

**Issue by myusufid** [accentinteractive/laravel-logcleaner#2]
Hi, in my project have some of logs that inside of directories
eg : `storage/logs/feature/user-1.log`

Actually I have try it, and it does not work on that log

I think this only work for the logs inside `storage/logs/*.log`

**Comment by accentinteractive** [comment]
I think you are right. That is actually a nice feature, that we will probably implement in the not too distant future.

If you are pressed for time, please feel free to create a merge request for it.

**Comment by accentinteractive** [comment]
We are working on this feature

**Comment by accentinteractive** [comment]
The feature was released into V 1.4.0.

Added support to handle logfiles in subfolders. Can be set in config `logcleaner.process_subfolders`. Is set to `true` by default.

- Trimming: all files in subfolder are trimmed
- Deleting: in each subfolder, all files except the N most recent ones. Where N equals `logcleaner.log_files_to_keep`
- Handling of subfolders is set to true by default, but can be overridden by `env('LOGCLEANER_PROCESS_SUBFOLDERS')`
